### ISSUE TITLE
Toolbar is squished

### ISSUE THREAD

**Issue by entrity** [entrity/tipsy-web-public#1]
See screenshot

![screenshot from 2015-07-14 12 07 04](https://cloud.githubusercontent.com/assets/950824/8711654/cec0ffba-2b08-11e5-99e3-d16994bcf541.png)

**Comment by sirtastic** [comment]
How do I get my dev environment access to the additional nav items?

**Comment by entrity** [comment]
@sirtastic Create additional user accounts so that you can flag an edit until it has enough flag points to be unpublished and need a review. Then log in as a user who did NOT flag the edit in question. That user should be eligible to vote in the review.

**Comment by entrity** [comment]
@sirtastic it looks like you addressed this. Please update the issue tracker.

**Comment by sirtastic** [comment]
Fixed
