### ISSUE TITLE
Give <body> ID to signed_in_home.html.erb

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#101]
Give `views/home/signed_in_home.html.erb` a custom body ID of `<body id="discover" ... >`

Want to customize the look of this page a bit.

**Comment by entrity** [comment]
commit 7328b90afea2f97eeb4b2443cdfe03a5b1f20657
Date:   Fri Sep 18 19:21:48 2015 -0700

    Give <body> ID to signed_in_home.html.erb. Closes #101 (github)
