### ISSUE TITLE
Images not displaying after being approved

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#109]
Uploaded a few images and had matt approve them however they never showed up on the life site.

**Comment by entrity** [comment]
@sirtastic : please provide record ids.

**Comment by sirtastic** [comment]
@entrity https://tipsyology.com/recipe/2817-desert-breeze

**Comment by entrity** [comment]
@sirtastic : Worked for me; dunno what Matt tried. Here's what I did:

- Went to https://tipsyology.com/recipe/2817-desert-breeze and verified that no photos appeared
- Went to https://tipsyology.com/admin/photos
- Clicked the 'publish' button on the row for Photo number 4.
  - The row changed from grey to yellow

Then I went to https://tipsyology.com/recipe/2817-desert-breeze again, and the photo was displayed.

![image](https://cloud.githubusercontent.com/assets/950824/10851172/d32e148e-7ee6-11e5-84a1-7a365ccf5961.png)


![image](https://cloud.githubusercontent.com/assets/950824/10851164/c7ff7832-7ee6-11e5-9e10-90df0ffa3ac9.png)

**Comment by entrity** [comment]
@sirtastic : Did you make sure to give Matt super powers? (See #97)

**Comment by sirtastic** [comment]
@entrity Matt does not have super powers. 

When I visit `https://tipsyology.com/admin/photos` logged in I get redirected back to homepage. I'm assuming I missing super powers.

**Comment by sirtastic** [comment]
@entrity On the quest to give myself super powers-- can you text or email me the root password, I don't want to reset it if I don't need to and can't find it anywhere.

**Comment by entrity** [comment]
@sirtastic : I don't have root pw, but I think ssh as root is disabled anyway (same as at new servers for pinney). But you *can* ssh in as user apache (which is what I do). The following 2 ssh keys of yours are in the apache authorized keys file:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCn0jtgIipkqNwocIfsToOcFp+yuusCcZTnCgYcX+OTKoGe5yaXXeL8QDoq66XESmylwPw+JU+1KkDNCYc7UGSlzboi/ST3VPu0vZboiQ61QmsXHQ8ngn7mdlAfCp3OE3RaCp6dlUe1jnk2646hdBin6SZRCWOUbtEWWV77bn/u9ksUlnTdJSCIeYp88GJlEdnP/38yFs9KPhaYYbiYSvdrGiF83/zFc4z9DK1ovdIe3avVAv79RdWbFZg8fqlCZF7VhqQai6MfzCrQ0oYLqAMCodvGftvtKv2sJ6qAjc3Wu028618IZtOVCNfHW6If6iscARxEygahBWZk80ERwLSMGtIOPCwqUIqxnQGrr1FUgi3GzqYFsKjkAMT5DScpBakeCnih4nI2xiqKsnEq2DDUxFmZDR6a17cwNGe9ekcwaoaLTubeKJtqfkZsIUFA+70CAA7beA+lq0YbiN1PruzYB0cku08Bpi2oLeR119QxdM5cKvlYr6wKbpYvxCg5TLv6lRAZfh7bHMRfQpdpo0mjLqFY6Dvb9m1z4Zdn970LpTU7jIqG60DnFABQUBFwTdchvfCvZR73LGvO3u/5rcgEHGKO6Wi9U2d2A1BFCe2tBc/q1a25eUKLTbnsiXCyLjDECsAyAxPuWoIQQDgIKQbo7y//RvdqMbbU3lZQDrZ5Gw== cameron.r.cunningham@gmail.com
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOSZDYuSkI5KiewK+EZ0cuAZwBj+qBlOj7cxP11yj8Khm+GOdF+J6IMH433yIUlTcYp5+OzMVNSZKYGLQhrytHQ+iXh1SLqbINm7IAVviTu5qlRRBeItp7pejAw8di3awmUn+H1RG8mZ4U+luuwiKYfKY6icigFAVbCMbVjEy9rdJUvzPtc/Otft/2VCE6WTwRi02c+4Kr6IyaXgaswNpkSVcaHINJWqnShDZwLTmWyEkxrG7xt+v7U2GIty5B5d1Y5DrRtazY0G1/7S79CqniTC/QqhkdKC9wQK+sr28P2G7bCF4iS3hkBkZ3N85VNmGCWv6sPPUAvMKbj5f0W1Bj sirtastic@ubuntu
```

**Comment by sirtastic** [comment]
@entrity This is not a secure page-- It's not a good idea to post SSH key in here, right?

**Comment by sirtastic** [comment]
@entrity From two different connections I tried to SSH into our linode only to have the connection time out. Even pinging the server times out... I'm using the SSH IP under the linode `Dashboard > Remote Access` replacing the root@ with apache@.

**Comment by sirtastic** [comment]
@entrity I broke something.  I reboot the server thinking it would be harmless. On the plus side I'm getting a response instead of just timing out when I try to SSH `Connection refused`

**Comment by entrity** [comment]
@sirtastic :

Don't worry about security; I only posted your public key, not private.

As for connection timeout, did you remember to connect to port 4000 (instead of 22)?

As for a failure after reboot, i'm surprised. Everything that we need should have initialize during start up. But I'll see if I can get into the machine and find the trouble today.

**Comment by sirtastic** [comment]
@entrity Was the port #-- success, just need site back up so I can play with commands.

**Comment by entrity** [comment]
@sirtastic : Roger that. Up and running again.

**Comment by sirtastic** [comment]
@entrity Hopefully final inquiry regarding this-- how do I identify a users ID number? 

I inspected my user profile image and I'm thinking it might be the /003/ ? (eg id #3)
system/users/photos/000/000/003/thumb/40a614ff3a5b4e3ba836e3381519d917.jpg?1441827540

**Comment by entrity** [comment]
@sirtastic : If I understand your question correctly, I think you can find your User id by visiting your profile page. In the following snapshot, I can see that my Id is 2.
![image](https://cloud.githubusercontent.com/assets/950824/11023262/a48dc78e-8628-11e5-92e3-5e56a26c84bf.png)

**Comment by sirtastic** [comment]
@entrity What I see is a bit different as I've given myself a username.  

![image](https://cloud.githubusercontent.com/assets/3707868/11025280/084ba0b4-864e-11e5-8130-2db28c3ee02b.png)

My ID was in fact 3 but I'm not sure if that is coincidence or not.

**Comment by entrity** [comment]
@sirtastic : sorry for the slow reply. Looks like you are indeed user 3.

Just made a fix for the failure of your URL path to show up there where mine did: 

```
commit 07ca6690e4899b3532a829f7a0fe6bf8137c6630
Merge: 7a87ccd c9fb693
Date:   Wed Dec 16 10:34:48 2015 -0800

    Merge branch 'fix/user-link'
```

:eyes: I also just deployed the fix to prod. It looks like that deploy included some old changes from both of us too. So be on the lookout for anything that went wrong.
