### ISSUE TITLE
Fix layout of users/edit page

### ISSUE THREAD

**Issue by entrity** [entrity/tipsy-web-public#11]
The `users/edit` page gets rendered inside of `layouts/devise`. Look at what gets rendered in your rails terminal output or `development.log`:

```
Started GET "/users/edit" for 127.0.0.1 at 2015-07-19 17:15:53 -0700
Processing by Users::RegistrationsController#edit as HTML
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
   (0.1ms)  SELECT "identities"."provider" FROM "identities" WHERE "identities"."user_id" = $1  [["user_id", 1]]
  Rendered devise/registrations/edit.html.erb within layouts/devise (10.2ms)
Completed 200 OK in 74ms (Views: 71.8ms | ActiveRecord: 0.3ms)
```
The layout is where the `<head>` and boilerplate (`<footer>` *et al.*) belong.

You can view the page source to confirm that these items are being written twice.

Please fix this. In the meantime, I'm getting js errors:

![image](https://cloud.githubusercontent.com/assets/950824/8768583/d07e93be-2e3a-11e5-934c-c35ee8d5118a.png)

**Comment by sirtastic** [comment]
@entrity All the form fields you had in place are currently duplicated and the old ones are commented out in the event I missed some important angular stuff when transferring them to the new design.

If everything in the un-commented-out input fields is working properly we can remove the commented-out section which should alleviate some (or all) of these errors.

**Comment by sirtastic** [comment]
Errors be gone.
