### ISSUE TITLE
Favourites Page

### ISSUE THREAD

**Issue by entrity** [entrity/tipsy-web-public#18]
@sirtastic, is this supposed to be a new tab on the user's page? If not, where's the link to take you to the page, and what's it going to look like?

**Comment by sirtastic** [comment]
@entrity I don't think this should be in initial launch unless you think it would be an easy/quick implementation.

Visually this will be much like Yummly.com execution:

Favorites directory:
![image](https://cloud.githubusercontent.com/assets/3707868/8896937/d85851b2-33bf-11e5-914c-5473c56fbf53.png)

Individual list:
![image](https://cloud.githubusercontent.com/assets/3707868/8896941/ede1eae8-33bf-11e5-998d-c79ceaa0db27.png)

**Comment by sirtastic** [comment]
@entrity Links to this page is in the sidebar (The <3 icon)

**Comment by entrity** [comment]
ommit a8f8dd3b6751982c278a75ed242eb8f9f32504f8
Date:   Sat Aug 15 20:47:33 2015 -0700

    Make FavouritesCollections store 4 best drink thumbnails; eliminate 'unsorted' FavouriteCollection. Fixes #18 (github)

commit 4475dc1b56ecedd83c2a678772bcf6c01df6da2e
Date:   Sat Aug 15 19:00:37 2015 -0700

    Implement favourites. Closes #18 (github)

----

@sirtastic : I've put together something that I think fits the bill. Badly needs styling, though. Be sure to look at the DOM and see where the images are looking for sources (b/c we need a default, i.e. fallthrough, image).

Reopen this if you find something is truly broken.

**Comment by sirtastic** [comment]
@entrity Re-opening. Need a way to launch the favorites list. Also, possibly isolated to my environment but adding a drink to favorites launched window and allowed me to label a list however the drink never showed on the list. The list also showed a "0' drinks. Possibly broken.

**Comment by entrity** [comment]
@sirtastic : Isn't it enough to access the favourites button from the right sidebar? You already put a button there. And if you really need one in the toolbar, can't you just copy the button from the sidebar instead of having me plug in the new button?

**Comment by entrity** [comment]
@sirtastic : Not broken. See description below screenshot.

![image](https://cloud.githubusercontent.com/assets/950824/9421948/5fe951a2-4834-11e5-961a-91933a8b5ad6.png)

### Adding favourites

1. **in drink view** click on heart to add current drink to favs
1. **on the collections view**, you will see a button to make a new collection, as well as a list of all your current collections
1. **on the collections view** if you want to create a new collection, click the button for that. afterward, it will take you right back to the collections view
1. **on the collections view** click on a collection to add the current drink as a favourite in said collection

### Viewing favourites

1. **in sidebar**, click on heart to view favs
1. **on the collections view**, click on a collection to view the drinks it contains
