### ISSUE TITLE
SEO URLs

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#22]
**Currently (undesirable):**
tipsyology.com/drinks/####

**For SEO we want (desirable):**
tipsyology.com/recipe/unique-drink-name

**unique-drink-name** is the drink name (eg, vodkatini)
tipsyology.com/recipe/vodkatini

**Comment by entrity** [comment]
Compromise: `/recipe/id-unique-drink-name`

Starting the significant path identifier with an ID is standard for big data sets b/c it allows optimization in db queries.

Closed by 912b4ceff4eba5f221b7790f6523ab88159cab97

**Comment by sirtastic** [comment]
That's fine
