### ISSUE TITLE
Adding ingredient to filters does not exclude ingredient from being added again

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#23]
Currently if you add an ingredient to search filters you can continue to add said ingredient over and over again.  It should be removed from the next search if added.

**Comment by entrity** [comment]
commit 4cd0a6015516e5e969cc0ac5f25ff180a603c88d
Author: Markham Anderson <quinesquines@gmail.com>
Date:   Sat Aug 1 11:45:35 2015 -0700

    Exclude selected ingredients from fuzzy finder's search results
