### ISSUE TITLE
Make ingredient on drink recipe a link

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#26]
Line 141 in show.html.erb

Link each ingredient name to respective ingredient page.

**Comment by entrity** [comment]
commit f6b2fdc7d7e23f386fad12d41a7ead3e6bf1764d
Author: Markham Anderson <quinesquines@gmail.com>
Date:   Sun Aug 2 10:06:20 2015 -0700

    Populate drink details in find-results.html
