### ISSUE TITLE
Apply "active" class to ingredient fridge/cart when in the fridge or cart

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#27]
When an ingredient is present in cart add an active class to associated buttons.

I can think of two places this needs to happen:
- the drop down for the filter/search tags
- ingredients page

**Comment by entrity** [comment]
Okay. I'll shoot for applying the classes `in-cabinet` (b/c the js calls it a cabinet instead of fridge) and `in-shopping` to ingredient spans in the fuzzy-finder and in `find-results.html` and in the Drinks' ingredients lists.

**Comment by entrity** [comment]
@sirtastic : I ended up using the class `in-sidebar` instead of `active` or either of the names I proposed in my previous post.

commit 5ae9f44b8d110f07a9a2c3c8ec773792cbe0c9f7
Author: Markham Anderson <quinesquines@gmail.com>
Date:   Sun Aug 2 16:21:26 2015 -0700

    Apply 'in-sidebar' class to ingredient in main container if ingredient also appears in cabinet or shoppingList. Closes #27 (github)

**Comment by sirtastic** [comment]
Looks like you added the class to the drink name.  This should be added to the buttons.

![image](https://cloud.githubusercontent.com/assets/3707868/9053355/d6a8c0b2-3a28-11e5-83a9-cafbb2aa16a6.png)

![image](https://cloud.githubusercontent.com/assets/3707868/9053372/f2be1cc0-3a28-11e5-816f-ad8321e04fb3.png)

**Comment by entrity** [comment]
@sirtastic : Now I understand. Okay, it now sets the class `active` on the buttons themselves.

commit c159543fd488061def036c547d7fd7350b4615a1
Date:   Wed Aug 5 15:12:59 2015 -0700

    For isInCabinet & isInShoppingList, apply 'active' class to button, not row. Closes #27 (github)
