### ISSUE TITLE
Add Ingredient button not working on drink edit page

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#28]
Add Ingredient button not working on drink edit page

**Comment by entrity** [comment]
commit 1f70d9913a475a950dcac2eeb5ea5a7594f6b22d
Author: Markham Anderson <quinesquines@gmail.com>
Date:   Sun Aug 2 09:52:51 2015 -0700

    Fix 'Add Ingredient' button on DrinkEdit page
