### ISSUE TITLE
Fix indentation home.html.erb

### ISSUE THREAD

**Issue by entrity** [entrity/tipsy-web-public#38]
I've seen inconsistent tabbing within files, and I've corrected a number of them.

By convention, ruby files (.rb, .html.erb) use 2 spaces.
By convention, html & js files (.html, .js) use 1 tab.

1. Please fix tabbing on `home.html.erb`
1. When working on any file where the convention is uncertain, please take note of what tabbing already exists in the file, and conform to that style.

**Comment by entrity** [comment]
@sirtastic : this is becoming a real problem. Your latest changes make depth of indentation totally inconsistent in `drinks/edit.html`, so that the opening tags don't have the same depth as the closing tags, and it's taking me forever to work on this page. Don't let this happen again.

**Comment by entrity** [comment]
@sirtastic : please.

**Comment by sirtastic** [comment]
@entrity Sublime doesn't change tab settings when i flip between different
files/code-- it's set at a "Tab Size: 2"   It's ridiculous to change it
every time I flip to a new tab that requires a different indentation size.
Am I missing something?

**Comment by sirtastic** [comment]
@entrity Also I'm looking at my code. Indentation appears fine and the same as the other HTML files I've viewed so I'm confused.  If a open/close tag was inconsistently indented, that was something I overlooked. Mistakes happen. Otherwise the tab size: 2 appears to be what we are using for HTML..?

**Comment by sirtastic** [comment]
@entrity Noticed something weird and wonder if this is causing the issues here.

**How the code looks in bitbucket:**
![image](https://cloud.githubusercontent.com/assets/3707868/9103617/230d8e64-3bb5-11e5-8efd-dfad9c656e50.png)

**How the code looks in my sublime:**
![image](https://cloud.githubusercontent.com/assets/3707868/9103625/2decf0cc-3bb5-11e5-8416-e523a4f340b5.png)

**Comment by sirtastic** [comment]
@entrity Closing this. My indentations look fine. Something funky going on elsewhere.

**Comment by entrity** [comment]
@sirtastic : they might look fine to you, but that's because your text editor's config is hiding the mismatch from you. You can't count on anyone else (read: 'me') seeing it the way you do. Bitbucket's representation is correct. When you `Ctrl+A` in sublime, what do you see?

![image](https://cloud.githubusercontent.com/assets/950824/9185984/a2aa687c-3f75-11e5-9026-ddcdde0a7ba7.png)

See how lines have both dots and dashes? That means you're using spaces *and* tabs. Indentation must always be only one or the other. (And in fact, some languages will choke if you use the wrong one.)

To get your sublime to perform language-specific spacing by default, you need to add a line to the config file for the language in question. This page shows how: http://mlo.io/blog/2012/08/23/language-specific-indents-sublime.html

However, if you're editing pre-existing files, your new config won't kick in b/c sublime will just adopt what the file is already using. Config for language-specific spacing will only help you on new files.

**Comment by sirtastic** [comment]
922b542 fix
