### ISSUE TITLE
Make "clear all" filter button clear all active filters

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#39]
![image](https://cloud.githubusercontent.com/assets/3707868/9052587/259eba42-3a1e-11e5-868a-5a0d77a296dc.png)

**Comment by entrity** [comment]
@sirtastic : this not a bug; you created the line of code for the clear all button and just never hooked into actual js functionality.

**Comment by entrity** [comment]
commit c83b085b67c6ddd8f74b054220cbc89f1b3e1591
Date:   Wed Aug 5 15:20:17 2015 -0700

    Support 'Clear all' button in find-results. Resolves #39 (github)
