### ISSUE TITLE
Error when upvoting an image (no count recorded)

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#41]
![image](https://cloud.githubusercontent.com/assets/3707868/9052647/d6fb8a18-3a1e-11e5-8836-9d2df1b73154.png)

**Comment by entrity** [comment]
@sirtastic : thank you! Someone actually submits the error from the console when there's a bug!

**Comment by entrity** [comment]
commit 289d23aaa5ed9f64ea9536cd9c3ca9cf7ef03afa
Date:   Wed Aug 5 15:38:41 2015 -0700

    Fix RailsSupport.errorAlert fn. Fixes #41 (github)
