### ISSUE TITLE
Large images for gallery

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#42]
Width of 1060px

Height of whatever

**Comment by entrity** [comment]
@sirtastic : if you want to regenerate your thumbnails/large/medium images after pulling this change, rake the following:

```
rake paperclip:refresh CLASS=Photo
```

commit b51b0bff6623ae9f8fcbd6129bdfc0d1bb3210e1
Date:   Wed Aug 5 15:54:15 2015 -0700

    Large images for Drink photo gallery. Closes #42 (github)
