### ISSUE TITLE
Comment name showing as "User #1", should be user name.

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#44]
Under user settings I've added the field "nickname" which should replace the users name throughout if supplied.

![image](https://cloud.githubusercontent.com/assets/3707868/9053315/73dba7ec-3a28-11e5-804b-aa69748e1944.png)

![image](https://cloud.githubusercontent.com/assets/3707868/9053308/5c3cb266-3a28-11e5-8a2e-957bb550ebe6.png)

**Comment by entrity** [comment]
@sirtastic : this is not a bug. It's showing 'User 1' because you have no nickname specified on your user acct.
