### ISSUE TITLE
Change name to nickname

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#45]
Change the name here to be the users nickname if they supplied one:
![image](https://cloud.githubusercontent.com/assets/3707868/9053242/3bd92668-3a27-11e5-9311-53c56861892b.png)

Also change it here:
![image](https://cloud.githubusercontent.com/assets/3707868/9053255/7e2ae588-3a27-11e5-867e-cce9ed591f24.png)

Eventually users will have a public profile page (circle above) where the users activity can be seen such as latest contributions, etc.  <-- this will come at a later update, not milestone 1.

**Comment by entrity** [comment]
@sirtastic : Okay, but this isn't a bug. You're just introducing a specification change.

**Comment by entrity** [comment]
@sirtastic : okay, there was a bug. Didn't realize my name there was static.

commit e0b4f264c86ae1fd755e8a0997fddfec4d7e1545
Date:   Tue Aug 4 14:56:03 2015 -0700

    Add users#show view

**Comment by sirtastic** [comment]
@entrity Needs to display the name if no nickname is supplied.   The nickname is more a privacy feature.

![image](https://cloud.githubusercontent.com/assets/3707868/9160327/22c41d66-3eed-11e5-9428-e7a289b5fe97.png)


![image](https://cloud.githubusercontent.com/assets/3707868/9160338/43513636-3eed-11e5-86cd-775cb8469d5e.png)

**Comment by entrity** [comment]
commit ee1795567f4ae937f18171b14596642f9471ec68
Date:   Mon Aug 10 15:04:26 2015 -0700

    Add angular factory User. Closes #45 (github)

**Comment by sirtastic** [comment]
@entrity I'm still seeing the same after pulling that commit.

**Comment by entrity** [comment]
@sirtastic : I'm not. Can you reproduce the error in QA (or just leave your computer running some morning)?

**Comment by sirtastic** [comment]
@I'll be around till 8am @ home -- reach out to me before then-- I can have gf wake computer from 8-9am

**Comment by entrity** [comment]
@sirtastic : sorry for my unavailability. See instructions on my latest messages on hipchat.

**Comment by sirtastic** [comment]
@entrity As per discussion. Require a "display name" on signup so we don't have ugly names on our site.  :-D

**Comment by entrity** [comment]
Please make that a new ticket.
