### ISSUE TITLE
Editing drink ingredients section doesn't show current ingredients + need a way to re-order ingredients

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#46]
This area should show the current ingredient + servings provided for the drink with an icon to remove the ingredient.  If it's easy enough, drag/drop to re-order ingredients would be useful. Otherwise we need a way to re-order the ingredients since some drinks require ingredients be added in a specific order.

![image](https://cloud.githubusercontent.com/assets/3707868/9075845/ec52daa0-3ace-11e5-9fbd-a14a5fd9a405.png)

**Comment by sirtastic** [comment]
Make sure you get my latest push to develop as I changed this page a bit.

**Comment by entrity** [comment]
@sirtastic : Needs some css magic from you. Use `git show <revision>` to see my changes (in case you want to identify what css to undo).

commit a500872b8e8e0b0a192e01193e0b14d57bfeb3f5
Date:   Wed Aug 5 19:13:35 2015 -0700

    Make drink ingredients sortable. Add drag-and-drop for ordering drink ingredients. Closes #46 (github)

**Comment by sirtastic** [comment]
@entrity I've remedied the CSS here in latest push.
