### ISSUE TITLE
Suggestion Logic vs Related Drinks Logic

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#48]
*This write-up is a work in progress, please review and lets discuss any limitations/problems.thoughts you have.*

### Suggestion Logic

* When user adds a specific amount of ingredients to the filter (maybe start with 3?) the system starts querying to determine what new ingredient will give them the largest number of cocktail creation options. 
* When the user has for example **vodka**, **orange juice**, & **sparkling wine** it will query all drinks that contain those ingredients (individually and as a whole) then determine what ingredient is most common among them and suggesting that. 
* It will ultimately suggest an ingredient that will open up largest number of cocktail opportunities to the user.
* **This is an incredibly important feature. I've yet to see it implemented by any of our competition and something we must figure out how to do.**

### Related Drinks Logic

* When a user is viewing a drink with 5 ingredients the system should query those ingredients against the db to find other drinks with similar ingredients.  
* If another drink has 4 of the 5 ingredients it would be a good match. 
* If another drink has all 5 of the same ingredients + another ingredient, it would be a good match.
* This might do better as a script we run that auto links similar drinks to a cocktail by creating a table under the cocktail and populating it with matches so this isn't something that runs on the fly using up tons of resources.

**Comment by entrity** [comment]
@sirtastic :
----
## Suggestion Logic

Are we suggesting an ingredient or drinks?

>When the user has for example **vodka**, **orange juice**, & **sparkling wine** it will query all drinks that contain those ingredients (individually and as a whole) then determine what ingredient is most common among them and suggesting that. 

But it could be that in every case, the most common ingredient doesn't complete any drinks. E.g. Maybe the most common ingredient is needed for another 30 drinks, but each of those drinks has 6 ingredients. Is this still what you mean?

----

## Related Drinks Logic 

commit a3e79e6b752f4c90cc0bdb9fc0d37c7848d6eb9a
Date:   Wed Aug 5 17:15:53 2015 -0700

    Add db column & rake task for related drinks. Resolves #48 (github)

**Comment by sirtastic** [comment]
@entrity 

> Are we suggesting an ingredient or drinks?

It is suggesting an ingredient to make new drinks. 

**Example:**
> "Hey, if you had **_________ ingredient** you can make **4 new cocktails**, want to add this ingredient to your shopping list?"

It's not suggesting the most common ingredient but rather suggest a single ingredient that can make them the most new cocktails.  Ideally we would suggest several new ingredients if possible. 

**Another example:**
> "You are **1** ingredient away from being able to make **4** new cocktails & **2** ingredients away from making **12** new cocktails. Want to add them to your shopping list?"

Hopefully that clears up confusion. Let me know.

**Comment by entrity** [comment]
commit ac33f1422380fd5110eae82b00942d792f540810
Date:   Mon Aug 10 14:42:13 2015 -0700

    Show related drinks at bottom of Drink show page. Addresses #48 (github)

commit 27924aa2fe16f2f64e028245118b24ff294bc961
Date:   Mon Aug 10 12:14:56 2015 -0700

    Limit Drink suggestions to a distance of 1. Addresses #48 (github)

commit 7ca0cfa09686fcdcd9acd987ba66eb64b895bba8\
Date:   Sun Aug 9 15:23:01 2015 -0700

    Implement Drink suggestions. Resolves #48

commit 7cd45ff990b1b5830deb884f0abe59572cbb8d98
Date:   Thu Aug 6 14:26:12 2015 -0700

    In rake drink:set_related, use ActiveRecord's ::find_each instead of ::all
