### ISSUE TITLE
JS error in drink edit page

### ISSUE THREAD

**Issue by entrity** [entrity/tipsy-web-public#49]
@sirtastic : have you noticed there's a js error on the edit page since your latest changes?"

![image](https://cloud.githubusercontent.com/assets/950824/9100177/774469e0-3b8c-11e5-9732-a7bb52f7d33f.png)

Looks like the problem is because you've undone support for Markdown. How do you want users to be able to specify formatting?

**Comment by sirtastic** [comment]
Not getting it anymore.
