### ISSUE TITLE
Made some changes to comments

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#54]
#  1
I moved the "Tips" section into `/drinks/comments.html`

It's not able to pull the drink name from there. Is there any way we can get this portion working from within that file?

![image](https://cloud.githubusercontent.com/assets/3707868/9154473/f2ee04ca-3e43-11e5-9652-9bebd5afcf38.png)

# 2

Comments placeholder text.  Make it show when no comment have been added. I added HTML `<span class="no-comments">` within `comments.html` file

![image](https://cloud.githubusercontent.com/assets/3707868/9154500/f9a7012e-3e46-11e5-9861-662376f59d98.png)

## That's all for now! You excited man? We are making a sweet app!

**Comment by entrity** [comment]
@sirtastic : Working on it, but please make a real priority of using consistent spacing/tabbing.  See screenshot:

![image](https://cloud.githubusercontent.com/assets/950824/9185984/a2aa687c-3f75-11e5-9026-ddcdde0a7ba7.png)

As you can see, this is a mix of tabs (4 spaces) and spaces (usually 2's), and the code doesn't line up when I try to work on it.

You can adjust tabbing easily with the quick menu. See screenshot:

![image](https://cloud.githubusercontent.com/assets/950824/9186055/5af04870-3f76-11e5-9440-64bd880244b2.png)

![image](https://cloud.githubusercontent.com/assets/950824/9186038/3d835dd6-3f76-11e5-9532-cec31724bb93.png)

**Comment by entrity** [comment]
commit ee1795567f4ae937f18171b14596642f9471ec68
Date:   Mon Aug 10 15:04:26 2015 -0700

    Add angular factory User. Closes #45 (github)

**Comment by entrity** [comment]
commit a49641079bdd1e443bcb0366fff7a406a63198c0
Date:   Mon Aug 10 20:48:07 2015 -0700

    Implement Comment tip votes

commit 27175e71b56225b8ffd156f79e3566c924a511e2
Date:   Mon Aug 10 15:45:20 2015 -0700

    Show Cameron's 'No Comments' div when comments are empty. Closes #54 (github)

**Comment by entrity** [comment]
@sirtastic : there are now 2 flag icons by comments. One is for *flag as inappropriate*; the other is for *flag as a tip*. Please take charge of changing the latter icon.

**Comment by sirtastic** [comment]
@entrity Question, how does flagging as tip work? Does it take multiple flags? Does it count them and display the most flagged? Does it require review?

I think we should make it say something like "Flagged as a tip by 2 users" and show comments flagged as "tips" in descending order in the "tips" section, most flags first.. Let me know if that's not already the case. Thoughts?

**Comment by entrity** [comment]
@sirtastic : a single flag will do it. More flags just makes a given tip appear above other tips in the tips section. It does not require review.

I don't recall if that's already the case ('Flagged as a tip by...'). Feel free to add that if it's not there.

**Comment by sirtastic** [comment]
@entrity Since I can't create an account in my environment I can't flag my posts as a "tip". Is there a command I can run to approve them so I can see how they are styled?

**Comment by entrity** [comment]
@sirtastic : just change the data directly. You'll probably want to do it in the spreadsheet view of pgadmin3, but here's how to do it on the `psql` command line. (The `tipsy=#` is the prompt. Don't actually type that.):

```
tipsy=# update comments set tip_pts = 1; # This will give all comments 1 tip point
tipsy=# update comments set tip_pts = 1 where id = 4; # This will give 1 tip point to comment #4
```
