### ISSUE TITLE
Similar drinks (on drink page) bug + enhancement

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#56]
The "likes" doesn't update.  I "liked" the drink picture and refreshed several times but it still said "0"

![image](https://cloud.githubusercontent.com/assets/3707868/9243859/4f1b6b94-414a-11e5-9b3a-ad6b93e596f9.png)

**Comment by entrity** [comment]
@sirtastic : in that box, I'm just showing how many upvotes the drink has. The icon doesn't do anything, just like the beaker icon to its left doesn't do anything.

I wouldn't give the user power to click the icon and upvote a related drink from this page. All they've seen about the related drink at this point is its name (and the number of required ingredients). For all they know, the recipe is terrible and they upvoted it on pure name recognition. If they want to upvote a drink (or for that matter, add it to their favourites), they should at very least follow the link to the drink page.

What are your thoughts?

**Comment by sirtastic** [comment]
@entrity Icons shouldn't do anything on-click but the one on the right should show the upvote count which in my testing it does not.

**Comment by entrity** [comment]
@sirtastic : votes will now increment/decrement the counts for upvotes and downvotes. If you want to set the counts to the number of votes already in your db, `rake drink:count_votes`.

commit ca0a162013ed8fd29da5a1a4e3a8e84d020d77ef
Date:   Fri Aug 21 18:15:34 2015 -0700

    Increment/decrement Drinks' up_vote_ct and dn_vote_ct on Vote creation. Fixes #56 (github)
