### ISSUE TITLE
Back button doesn't work most of the time

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#57]
If you navigate to a new drink using similar drink cards at the bottom of a drink page you are unable to go back with the back button. Incredibly annoying.  Probably happening in other places as well.

**Comment by entrity** [comment]
k. turbolinks have given me no end of trouble. i'll just remove the turbolinks js entirely.

**Comment by entrity** [comment]
commit cecd3b742d148022b02e0446ea096aac73255a54
Date:   Fri Aug 14 18:03:58 2015 -0700

    Remove Turbolinks. Fixes #57 (github)
