### ISSUE TITLE
Clicking comment looks like it does nothing

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#59]
Clicking comment looks like it does nothing.  This results in multiple clicks and duplicate posts. Maybe refresh page or in an angular way display the comment?

**Comment by entrity** [comment]
commit 99eabfdbebefd21dcba11abd951a6683defa08a2
Date:   Mon Aug 17 18:46:07 2015 -0700

    Disable comment submission form while waiting on server for previous comment submission (client side)
