### ISSUE TITLE
Changing profile picture doesn't update everywhere

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#60]
![image](https://cloud.githubusercontent.com/assets/3707868/9287563/5d9f039c-42d0-11e5-9ae7-fe1106c98e77.png)

Updated in top/right corner and for comment textbox area but not on comments/tips.

**Comment by entrity** [comment]
commit f03921da3b4a30b6c8b1504e211237a5bf24ad23
Date:   Fri Aug 21 16:27:19 2015 -0700

    Denormalize User avatar and name onto Comments when updated. Fixes #60 (github)
