### ISSUE TITLE
Too many drinks showing on "similar to" part

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#61]
https://ec2-54-148-198-156.us-west-2.compute.amazonaws.com/recipe/8900-spring

* Lets have it show 6 to start with a button "Show more similar drinks". 
* On click it adds 6 more. 
* User can keep clicking it till we run out of similar drinks.

**Comment by entrity** [comment]
@sirtastic : odd. There should always be only 5 or fewer 'similar drinks'. I'll look into it.

**Comment by entrity** [comment]
Data issue. Had imported the drinks table dump into the wrong schema. Ended up changing the dump file to specify `SET search_path = deploy, pg_catalog;`
