### ISSUE TITLE
Add "Display name" to sign-up and require it, use it throughout for the users name (aka nickname)

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#65]
Title says it all.

**Comment by entrity** [comment]
@sirtastic : I think by the nature of the compromise, we include the nick textfield in the signup form but make it optional. Does that sound accurate?

**Comment by sirtastic** [comment]
@entrity I'll compromise with you if you default no-names and no-nicknames to **"Anonymous"** so we don't have "User ####" all over.

**Comment by entrity** [comment]
@sirtastic : :ok:

**Comment by entrity** [comment]
commit 3dfefc2e443bcc25a75bc3754e28e9b55d0fe5de
Date:   Fri Aug 21 16:01:04 2015 -0700

    Include 'nickname' input in User registration form. Use name 'Anonymous' instead of 'User #X' for fallback value in js fn User.getNickname(). Resolves #65 (github)
