### ISSUE TITLE
Plugin flag count

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#66]
![image](https://cloud.githubusercontent.com/assets/3707868/9401388/6297491a-4783-11e5-95b9-ea8188f3d504.png)

**Comment by entrity** [comment]
@sirtastic : done, but you've still got a css rule setting `opacity: 0`

commit 927e0e6ce74e8cf03a1523b6d3f6d8de561bad4d
Date:   Fri Aug 21 15:50:24 2015 -0700

    Plug in flag_pts for each tip in comments.html. Resolves #66 (github)
