### ISSUE TITLE
Bring back flagging comments & differentiate icons for 'inappropriate' flag vs 'tip' flag

### ISSUE THREAD

**Issue by entrity** [entrity/tipsy-web-public#68]
1. Would you choose a different 'tip' icon? (At very least `fa-flag-checkered`. Maybe `fa-map-pin`, `fa-thumb-tack`, `fa-map-marker`) The language could even omit the word 'flag', as in *Was this comment helpful? Pin/mark/boost/hi-five/vote/check/designate it as a tip.* I really think we need a different icon for the tips button because everywhere else on the page, `fa-flag` means 'Flag as inappropriate'
2. It seems that your changes have made the 'Flag as inappropriate' button disappear from the comments (except when the cursor hovers over the flaggable comment). This is a valuable button b/c it's the only way that users can cooperatively unpublish a spammy user's comments. Would you please restore it.

**Comment by sirtastic** [comment]
Just pushed fix for Part 1. 

Part 2 is intentional.  Flagging a inappropriate is not a primary action and doesn't need to stand out in the design. I considered putting it in a dropdown menu (along with delete) like Facebook/twitter/etc do.  Users will discover it, it's common place to hide it.
