### ISSUE TITLE
Fix layout for mobile

### ISSUE THREAD

**Issue by entrity** [entrity/tipsy-web-public#69]
Looks like we either need some media queries or we are missing a meta tag somewhere b/c the mobile view is showing up at the same zoom as the desktop view:

![image](https://cloud.githubusercontent.com/assets/950824/9425252/024c0540-48bf-11e5-8944-716837e32f30.png)

**Comment by sirtastic** [comment]
@entrity Website does have media queries and viewport options. Should look different on an actual mobile device (does on mine) compared to a desktop.
