### ISSUE TITLE
Closing angular bootstrap modal (how?)

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#71]
`<button type="button" class="close" ng-click="close()">&times;</button>`

The above code doesn't seem to do it.  I've added this to the flagging revision modal (the view you see when there is no revisions). If you can modify/make that work and let me know so I can apply it elsewhere that'd be great.

**Comment by entrity** [comment]
```
<button type="button" class="close" ng-click="$close()">&times;</button>
```

Should work in most cases. Note the `$` in the `$close()` call.

**Comment by sirtastic** [comment]
Dang I was pretty `$close()`
