### ISSUE TITLE
Plugin "STEPS" for NEW drink

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#72]
You got the edit drink page going, need the new drink page **steps** plugged in:

![image](https://cloud.githubusercontent.com/assets/3707868/9456339/236f5114-4a8b-11e5-9b5d-582ae37b1dc7.png)

**Comment by entrity** [comment]
@sirtastic : sorry about that. Here's a quick fix. Please reopen this issue if you find anything else not working for the directions inputs in the form.

commit a5541feac74fb3dc1bc7d5db34afabbad8f47956
Date:   Mon Aug 24 18:25:31 2015 -0700

    Initialize revision.steps in Revision factory (js). Fixes #72 (github)
