### ISSUE TITLE
Make similar drink cards show image if it has one

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#74]
Use fallback icon (current look) when no image is available. 

![image](https://cloud.githubusercontent.com/assets/3707868/9470254/00829a2e-4b00-11e5-8566-3b1e3c66ee01.png)

**Comment by entrity** [comment]
commit 3c50f868e3f79ebe081c20eecc64243b54e696e2
Date:   Tue Aug 25 14:19:19 2015 -0700

    Include photos for related drinks at bottom of drinks#show. Closes #74 (github)
