### ISSUE TITLE
"New Drink" builder should open with 1 ingredient by default

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#76]
One of your last commits removed the default.

![image](https://cloud.githubusercontent.com/assets/3707868/9485134/0e65f8ec-4b6a-11e5-862c-c9af7826789b.png)

**Comment by entrity** [comment]
@sirtastic : not a bug. just part of the previous requirements. I can make this change tho

**Comment by entrity** [comment]
commit 895138bf54542f0ce32cbc92347e4293835ee62d
Date:   Wed Aug 26 10:07:35 2015 -0700

    "New Drink" builder should open with 1 ingredient by default. Closes #76 (github)
