### ISSUE TITLE
Logging in still lands me on this page

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#78]
![image](https://cloud.githubusercontent.com/assets/3707868/9485601/bde91b9a-4b70-11e5-9f99-6b7173657d62.png)

**Comment by entrity** [comment]
commit 949d8f52fd600e6fe7cb70ffa35ee7d5c690da2a
Date:   Wed Aug 26 10:04:14 2015 -0700

    Prevent login from leading to '/reviews/count'. Fixes #78 (github)
