### ISSUE TITLE
Ingredients alias data

### ISSUE THREAD

**Issue by entrity** [entrity/tipsy-web-public#8]
@sirtastic, I need your or Matt or someone to go through the spreadsheet at https://bitbucket.org/entrity/tipsy-web/downloads/ingredients.csv and indicate 'alias' relationships, i.e. ingredient X is just an alias of ingredient Y, not really a distinct ingredient. 

For instance, there are 179 vodka entries, including the following:

```
   31 , Finlandia® vodka
   42 , Absolut® vodka
   56 , Skyy® Blue vodka
   57 , Smirnoff® vodka
   79 , Absolut® Citron vodka
   93 , Stoli® Vanil vodka
  110 , lemon vodka
  137 , Blavod® vodka
  147 , Smirnoff® watermelon vodka
  150 , Smirnoff® Lime Twist vodka
```

...A lot of these should really be interchangeable so that when searching for 'vodka', the user can see drinks that make use of `Finlandia® vodka` and `Absolut® vodka` and `Smirnoff® vodka` etc.

**Here's what I need you to do:**

1. Make a third column in the spreadsheet. (You could call it `canonical id` or something like that.)
1. For each row in the spreadsheet, if the ingredient at hand (e.g. `Blavod® vodka`) should be an alias for another ingredient (e.g. `vodka`), then in the third column, indicate the id of the canonical ingredient (`vodka`'s id). In this example, we've decided that `vodka` is the canonical ingredient, so it has a blank third column; i.e. it's not an alias for anything else, but many other entries are aliases for it.

**Comment by sirtastic** [comment]
Started work on this. 

Something I noticed. TONS of applicable aliases to use which from a marketing perspective is a goldmine.  For instance rum comes in like 20 flavors (vodka as well). Bacardi as an example makes a rum for each flavor (some uniquely there's too). In many cases you wouldn't even guess you had options for "currant rum", if you saw the cocktail called for "Bacardi currant rum" you would most likely go out and buy that brand rum! 

Anyways, I think this has a VERY strong marketing sales point :)

**Comment by entrity** [comment]
@sirtastic : I'm looking for the spreadsheet with the data. Can you provide a link to it or put it on the bitbucket downloads page or something?
