### ISSUE TITLE
Similar drink bug?

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#80]
Drink I'm viewing showed up as a similar drink?

![image](https://cloud.githubusercontent.com/assets/3707868/9510383/e7d22730-4c1f-11e5-9f5a-9a24169eb42a.png)

**Comment by entrity** [comment]
@sirtastic : Fixed. Need to run `rake db:set_related` on your machine to update your data. Could take ~3hrs.

commit eb4196ba239b0df2f361e7d3f5ce5ee4856f2ff7
Date:   Fri Aug 28 19:00:20 2015 -0700

    Fix rake task drink:set_related so that related_drink_ids excludes the primary drink id. Fixes #80 (github)
