### ISSUE TITLE
Get SSL cert signed

### ISSUE THREAD

**Issue by entrity** [entrity/tipsy-web-public#82]
1. Get the certificate signing request from the bitbucket downloads page: https://bitbucket.org/entrity/tipsy-web/downloads/ca.csr
1. Get GoDaddy to sign it. See instructions at https://www.godaddy.com/help/request-an-ssl-certificate-562
1. Put the signed certificate up on the downloads page (or just sftp it to the new production server)

**Comment by sirtastic** [comment]
@entrity Looking into SSL it seems pointless.

Most sites don't appear to use any SSL (stackoverflow, food.com, yummly, etc). 

Is there a reason you want to do this?

**Comment by entrity** [comment]
@sirtastic :

> The only reason is to prevent passwords. Without SSL, people's passwords (and all their data) can be sniffed. We don't have to do it if you don't want to do it. (It will take some code changes on my part if we don't do it, but it's a manageable scope.)

This one's up to you. Let me know.

**Comment by entrity** [comment]
@sirtastic : The server is up and running halfway between ssl and no-ssl.

If you do want a signed cert, I need to update the apache config to support https and use the signed cert. Otherwise, I need to update the tipsy code so that SSL is not required and update the facebook app config so that it redirects to http instead of https.

Let me know what you want. :shaved_ice:

**Comment by entrity** [comment]
@sirtastic : Oh, and I need you to update the DNS: make an A record and an MX record which point to the ip address 45.79.75.100

**Comment by sirtastic** [comment]
@entrity I'll figure out cert stuff and get DNS updated later this evening if that's okay

**Comment by sirtastic** [comment]
@entrity 1and1.com (registrar) doesn't let you input an IP address for a DNS as its considered and invalid hostname (nameserver).

**Comment by entrity** [comment]
@sirtastic :

**re dns** Correct. You aren't supposed to specify a nameserver by an IP. But your DNS task is not to specify a nameserver at all. You need to specify an A record and an MX record on an existing nameserver.

**re ssl** I just posted this to hipchat, but I'll repeat it here:

>The largest security risk is that a lot of people repeat passwords; if someone submits a form with their password and it's the same password they use somewhere else, anybody can sniff that pw and try to use it to get into that person's email etc.
>...
>Just checked on SO, and there's more to the story: they don't require SSL when browsing around, but they do require it when submitting the login form.
Looks like they're trying to protect just this sort of thing.

Bottom line: looks like we should pay to have our cert signed. 1and1 may offer cert signing. If not check out their knowledgebase or customer support for how to get a cert signed.

**Comment by sirtastic** [comment]
@entrity I can specify an MX record with bluehost (who is hosting the current site live @ www.tipsyology.com .. This is for email forwarding, correct?

**Comment by sirtastic** [comment]
See picture. I can specify an "A" record but not sure what it should be labeled as and if it should be replacing any of the currently listed records.  As for MX record, using same list the IP address was refused "IP addresses are not allowable destination values.".

![Uploading image.png…]()

**Comment by sirtastic** [comment]
@entrity Do we want the green bar?

**Comment by entrity** [comment]
@sirtastic, not worth the greenbar if it costs extra.

Does 1and1 not offer free nameserver service? What were the ns before you set them to bluehost's ns?

Bluehost definitely won't provide the ns service we need since we aren't going to host with them.

As for MX, no, We don't need it for email forwarding. It's because our application server is going to be sending out confirmation emails to all the users who sign up, and A lot of the recipient email services will reject those emails unless they can find a reverse DNS match.

**Comment by sirtastic** [comment]
@entrity Green bar = $230sh (low) to $299 (high)

No green bar = $39sh - $50sh

**Comment by sirtastic** [comment]
@entrity So I set it back to defaults with 1and1 and got access to MX records though A (host) isn't anywhere to be seen. Once again it will not accept an IP address.

What are we trying to do with this IP address? I'm a bit confused here.  Message me on hipchat if you are available so we can figure this out and I don't know what the purpose of this is.

**Comment by entrity** [comment]
@sirtastic : do you have the signed ssl cert?

I went to comodo to download it this morning, but they say it's already been downloaded:

![image](https://cloud.githubusercontent.com/assets/950824/9700263/4243d6b2-53b1-11e5-8f49-0e02c720983b.png)

If you'll provide the signed cert, I'll put it in the right place on the server. (You can put it on the Downloads page of our bitbucket repo or just put it in the home folder of cameron@tipsyology.com (scp or sftp it).
