### ISSUE TITLE
Analytics code

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#87]
Insert to all pages:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66931968-1', 'auto');
  ga('send', 'pageview');
</script>
```

**Comment by entrity** [comment]
@sirtastic : added. Would you add me as a user on the analytics for this site?

commit 8e6e901b38e1bb640f036007edcb7552811e1344
Date:   Mon Aug 31 09:06:58 2015 -0700

    Add Google Analytics tracking snippet. Closes #87 (github)

**Comment by sirtastic** [comment]
@entrity Failed to verify with webmaster tools.  Added you as analytics users.

![image](https://cloud.githubusercontent.com/assets/3707868/9596780/7b110982-502e-11e5-8243-329e104ca065.png)

**Comment by entrity** [comment]
The code changes were made back when I posted; they just haven't been deployed. You can investigate any changes I post about by referencing the commit hash that I include in my posts.

You're free to deploy to production if you don't want to wait until my next deploy: `cap production deploy`. As you can see with `git b --contains 8e6e901b38e1bb640f036007edcb7552811e1344`, it's on the develop branch but not master, so you'll have to merge develop to master.
