### ISSUE TITLE
Production showing toooons of drinks in similar drinks (for PEZ) at the least

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#88]
![image](https://cloud.githubusercontent.com/assets/3707868/9586241/6addb1d6-4fd0-11e5-9506-21f3c05e1d1e.png)

**Comment by entrity** [comment]
commit 1f5c414df4d278bf5cd6953bd9f6eaebc93447e6
Date:   Mon Aug 31 14:57:58 2015 -0700

    Call GC in rake drink:set_related. Ajax: only fetch relatedDrinks if related_drink_ids array is not empty. Fixes #88 (github)

commit 5de65acb97786cc07615d3418049a652b34224be
Date:   Tue Sep 1 14:28:50 2015 -0700

    In rake drink:set_related, set active_record.identity_map = false, perform work within block of ActiveRecord::Base.uncached do ... end. Fixes #88 (github)

**Comment by entrity** [comment]
Still running a test on this one. It should finish in 5 hours if successful.
