### ISSUE TITLE
Error/notice bar display regardless of being populated with content

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#90]
Can we not have this bar *not* be a permanent addition to the pages so I can style it?  I've added a padding to it and now it's always visible.

![image](https://cloud.githubusercontent.com/assets/3707868/9594225/3d5a9c32-500d-11e5-81f5-c0aab9cca1d7.png)

**Comment by entrity** [comment]
Use CSS `:empty`

http://www.w3schools.com/cssref/sel_empty.asp
