### ISSUE TITLE
Hide button on click

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#91]
Using some copy/paste angular from stackoverflow I've made this button show the form when clicked.  Can you be fantastic and hide the button when it's clicked (still preserving the showing of the form)

![image](https://cloud.githubusercontent.com/assets/3707868/9594576/5b2b0252-5011-11e5-97f0-175d49d7155a.png)

**Comment by entrity** [comment]
commit f0d17545d10f9e4b73ce96defa0f7cd4e64d8ba3
Date:   Fri Sep 18 19:25:19 2015 -0700

    Hide 'sign up with email' button on click. Closes # 91
