### ISSUE TITLE
Confirmation email was in spam folder and link was not clickable

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#93]
Was searching spam when I found the tipsyology confirmation email.  I moved it to my inbox and the "Confirm my account" link was not clickable. Shows as a different color but no href on it.

**Comment by entrity** [comment]
No href? Can you view as html and post the body? My experience was not so.

**Comment by sirtastic** [comment]
@entrity Possibly caused by google mail weirdness.  Since it was initially considered spam the href was removed. After I moved it to inbox it remained remove for a while.  Upon viewing it today, the href was present. 

 I just tried once more creating an account using a new email (sirtastic@) and never received any confirmation.  I have that account linked to my main account which is why I never received anything, it went straight into spam box for sirtastic@ and was never forwarded.  

We need to figure out how to get @tipsyology.com whitelisted, any ideas?

**Comment by entrity** [comment]
Addressing in #98
