### ISSUE TITLE
Nano Scrollbar JS weirdness

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#94]
The only way I could get the nano scrollbar to work as to place it in the sidebar.html file.  Pretty sure this isn't where it should go, could you move to appropriate area.  See weirdness in the attached pic.

See image:

![image](https://cloud.githubusercontent.com/assets/3707868/9751813/1ef335ea-565e-11e5-9d20-8e986b4b68f2.png)

**Comment by entrity** [comment]
@sirtastic : I have your code, but I don't see the bad behaviour:

![image](https://cloud.githubusercontent.com/assets/950824/9776279/ae5d3d68-570b-11e5-9c13-125aa1daa81e.png)

![image](https://cloud.githubusercontent.com/assets/950824/9776284/bdfa199e-570b-11e5-87f1-2b190f7c4c34.png)

Do you still have it after you clear your cache?

**Comment by sirtastic** [comment]
@entrity Look at your image (its in black text color, I changed it to white on my screen so you could see).

**Comment by entrity** [comment]
@sirtastic : Okay. I guess we aren't to use `script` tags inside of included html files, only in non-ajax-fetched html.

commit c6325457fa8c28fe70b015dd5a9d73f4166ba0da
Date:   Fri Sep 18 19:41:25 2015 -0700

    Call js nanoScroller in angular onload for rightbar. Closes #94
