### ISSUE TITLE
Fridge sidebar not working unless logged in

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#95]
Shows up empty and user is unable to add ingredients to it unless logged in.

![image](https://cloud.githubusercontent.com/assets/3707868/9751857/ba050504-565e-11e5-9d16-90daad29d82e.png)

**Comment by entrity** [comment]
@sirtastic : I have the latest code on master, and I'm not able to get the right sidebar to appear when not logged in:

![image](https://cloud.githubusercontent.com/assets/950824/9776324/142a6a9e-570c-11e5-971b-a3fed4c99b26.png)

Back to you.

**Comment by sirtastic** [comment]
@entrity sidebar is visible in my branch only atm. Haven't merged that to
develop. My bad.

**Comment by sirtastic** [comment]
It's merged to develop. @entrity

**Comment by entrity** [comment]
commit d860b4d1753d5464690fc58b3c8f4b63c0779822
Date:   Fri Sep 18 20:03:57 2015 -0700

    Require signed in for drinks#new/edit/create/update/destroy. Show fridge & shopping list even when user is not logged in. Closes #95
