### ISSUE TITLE
Bugs when updating drink

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#99]
http://tipsyology.com/recipe/5055-pina-colada

Updated content for this drink and few issues seem to show after you approved it.  

1) image didn't appear, upload showed success.
2) Duplicated ingredients. Bottom 3 were my updates to the servings.
3) Directions appearing incorrectly. 

![image](https://cloud.githubusercontent.com/assets/3707868/9774607/77e474e8-56fe-11e5-9e9c-942da049424c.png)

**Comment by entrity** [comment]
@sirtastic : The pic is never going to show up until it's been reviewed and approved.

**Comment by entrity** [comment]
@sirtastic : I'll see if I can fix the other things.

**Comment by entrity** [comment]
@sirtastic : sorry about these errors. The ingredients issue didn't show up in testing b/c it only affected drinks that had never been revised before.

commit 0eac0ced8ed632f7cf5abe4121daabf6a4198312
Date:   Wed Sep 9 15:28:35 2015 -0700

    Fix duplication of ingredients when making first Revision on a Drink. Fixes #99

commit 3832779240982c74ee8d6e7db9ab0d8586336613
Date:   Wed Sep 9 15:24:03 2015 -0700

    Fix display of recipe directions. Fixes #99

**Comment by sirtastic** [comment]
@entrity The pina-colada drink is still displaying the duplicates. Can you fix and close?

**Comment by entrity** [comment]
@sirtastic : that's a data issue. Just make a revision (after I made the code changes) and publish it.
